# Generated by Django 5.1.6 on 2025-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employess_birthdate_alter_employess_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employess',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
