# Generated by Django 5.1.6 on 2025-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employess_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employess',
            name='DNI',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employess',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
